### ISSUE TITLE
'HID_USAGE_PAGE_VENDOR_SPEC' record has two bytes

### ISSUE THREAD

**Issue by alitekin2fx** [IntergatedCircuits/HidReportDef#2]
Hi Benedek, thank you for the great USB libraries. As far as I know the vendor-defined page records have three bytes (0x06, 0x00, 0xFF). But why the HID_USAGE_PAGE_VENDOR_SPEC macro has only two bytes?

**Comment by benedekkupper** [comment]
Hi!
It looks like an oversight from my side, since the vendor defined usage page range is between FF00 and FFFF. Thanks for bringing this to my attention, I will get this fixed (removing this macro, since there's no single page for vendor functionality).
